name: "Blockquote"
identifier: "com.brettterpstra.popclip.extension.blockquote"
description: "Turn indented text into nested Markdown blockquote."
icon: "blockquote.png"
title: "Quote"
javascript file: "blockquote.ts"
after: "paste-result"
requirements: ["paste"]
popclipVersion: 5997
keywords: markdown quote blockquote
