name: "Outdent"
identifier: "com.brettterpstra.popclip.extension.outdent"
description: "Outdent the selection."
icon: "outdent.png"
title: "|<"
javascript file: "outdent.ts"
after: "paste-result"
requirements: ["paste"]
