name: "CopyURLS"
identifier: "com.brettterpstra.popclip.extension.copyurls"
description: "Copies only urls in selection to a list in the clipboard."
icon: "icon.png"
title: "CopyURLS"
regular expression: "(?si)(.*)?((http|https):\\/\\/)?[\\w\\-_]+(\\.[\\w\\-_]+)+([\\w\\-\\.,@?^=%&:/~\\+#\\(\\)_]*[\\w\\-\\@^=%&/~\\+#])?(.*)?"
javascript file: "script.ts"
after: "copy-result"
popclipVersion: 5997
keywords: url links extract clipboard
