name: "Wrappers"
identifier: "com.brettterpstra.popclip.extension.wrapper"
description: "Too many wrappers"
icon: "wrapped.png"
title: "wrap"
shell script file: "script.rb"
script interpreter: "/usr/bin/ruby"
after: "paste-result"
requirements: ["paste"]
options:
  - identifier: "popmakerprefix"
    type: "string"
    label: "Prefix"
  - identifier: "popmakersuffix"
    type: "string"
    label: "Suffix"
  - identifier: "popmakeroptprefix"
    type: "string"
    label: "⌥ Prefix"
  - identifier: "popmakeroptsuffix"
    type: "string"
    label: "⌥ Suffix"
  - identifier: "popmakercmdprefix"
    type: "string"
    label: "⌘ Prefix"
  - identifier: "popmakercmdsuffix"
    type: "string"
    label: "⌘ Suffix"
