name: "md2mm"
identifier: "com.brettterpstra.popclip.extension.md2mm"
description: "Convert text/outlines to tab-indented outlines for pasting into mind maps."
icon: "md2mm.png"
title: "md2mm"
shell script file: "md2mm.rb"
script interpreter: "/usr/bin/ruby"
after: "copy-result"
