name: "FixPoorlyObscuredEmail"
identifier: "com.brettterpstra.popclip.extension.fixemail"
description: "Fix or open AT DOT obscured email addresses."
title: "DOT"
regular expression: "(?si)(.*)AT\\s+[a-z0-9]+\\s+DOT(.*)"
shell script file: "script.rb"
script interpreter: "/usr/bin/ruby"
after: "paste-result"
