name: Editor
identifier: com.brettterpstra.popclip.extension.editor
description: Adds ins, del and mark tags to text
icon: icon.png
requirements: [paste]
submenu:
  - title: Mark
    identifier: mark
    shell script file: script.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
  - title: Insert
    identifier: insert
    shell script file: script.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
  - title: Delete
    identifier: delete
    shell script file: script.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
  - title: Comment
    identifier: comment
    shell script file: script.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
options:
  - identifier: includedatetime
    type: boolean
    label: Include Datetime
    default value: true