name: "CopyPLUS"
identifier: "com.brettterpstra.popclip.extension.copyplus"
description: "Append selection to clipboard."
icon: "copyplus.png"
title: "CopyPLUS"
shell script file: "copyplus.sh"
script interpreter: "/bin/bash"
popclipVersion: 5997
keywords: clipboard copy append
