name: "OpenURLS"
identifier: "com.brettterpstra.popclip.extension.openurls"
description: "Open all urls in selection."
icon: "openurls.png"
title: "OpenURLS"
regular expression: "(?si)(.*)?((http|https):\\/\\/)?[\\w\\-_]+(\\.[\\w\\-_]+)+([\\w\\-\\.,@?^=%&:/~\\+#\\(\\)_]*[\\w\\-\\@^=%&/~\\+#])?(.*)?"
javascript file: "openurls.ts"
after: "show-status"
