name: "Code"
identifier: "com.brettterpstra.popclip.extension.code"
description: "Convert to Markdown inline code or code block."
icon: "code.png"
title: "<>"
javascript file: "code.ts"
after: "paste-result"
requirements: ["paste"]
