name: "Code"
identifier: "com.brettterpstra.popclip.extension.code"
description: "Convert to Markdown inline code or code block."
icon: "code.png"
title: "<>"
shell script file: "code.rb"
script interpreter: "/usr/bin/ruby"
after: "paste-result"
requirements: ["paste"]
