name: "Twitterify"
identifier: "com.brettterpstra.popclip.extension.twitterify"
description: "Converts @names and #hashtags to x.com urls."
icon: "icon.png"
title: "Twitterify"
regular expression: "(?si)(.*)?(?:\\s|^)[@#]\\w+(.*)?"
javascript file: "script.ts"
after: "paste-result"
requirements: ["paste"]
options:
  - identifier: "usemarkdown"
    type: "boolean"
    label: "Markdown Links"
    default value: true
popclipVersion: 5997
keywords: hashtag mention links
