name: "Markdownify"
identifier: "com.brettterpstra.popclip.extension.markdownify"
title: "2MD"
shell script file: "markdownify.py"
script interpreter: "/usr/bin/python"
after: "paste-result"
requirements: ["paste"]
popclipVersion: 5997
keywords: markdown convert html
