name: "URLEncode"
identifier: "com.brettterpstra.popclip.extension.urlencode"
description: "Percent encode selected text."
title: "%"
javascript file: "urlencode.ts"
after: "paste-result"
requirements: ["paste"]
