name: Comment
identifier: com.brettterpstra.popclip.extension.comment
description: Turn selected text into an HTML/code comment.
icon: comment.png
requirements: [paste]
submenu:
  - title: <!--
    identifier: html
    shell script file: comment.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
  - title: /*
    identifier: css
    shell script file: comment.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
  - title: "#"
    identifier: hash
    shell script file: comment.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
  - title: //
    identifier: slash
    shell script file: comment.rb
    script interpreter: /usr/bin/ruby
    after: paste-result
    requirements: [paste]
