name: "Increment Templated"
identifier: "com.brettterpstra.popclip.extension.incrementtemplated"
description: "Repeat text by incrementing template values."
icon: "increment.png"
title: "Increment"
regular expression: "(?mis)^(.*?)##(\\d+(\\.\\.\\d+)?\\.\\.\\d+|(.+,)+.+)##(.*)$"
javascript file: "script.ts"
after: "paste-result"
requirements: ["paste"]
