name: "PoorText"
identifier: "com.brettterpstra.popclip.extension.poortext"
description: "Strip rich text formatting"
icon: "icon.png"
title: "PoorText"
javascript file: "script.ts"
after: "paste-result"
requirements: ["paste"]
popclipVersion: 5997
keywords: plaintext formatting strip
