name: "Sum"
identifier: "com.brettterpstra.popclip.extension.sum"
description: "Totals all numbers found in selection."
icon: "icon.png"
title: "Sum"
regular expression: "(?s)(.*)?\\d+(.*)?"
javascript file: "script.ts"
after: "copy-result"
options:
  - identifier: "separator"
    type: "string"
    label: "Separator"
    default value: ","
  - identifier: "delimiter"
    type: "string"
    label: "Decimal Delimiter"
    default value: "."
  - identifier: "formatoutput"
    type: "boolean"
    label: "Format Output"
    default value: false
popclipVersion: 5997
keywords: math total numbers
