name: "HardWrap"
identifier: "com.brettterpstra.popclip.extension.hardwrap"
description: "Add and remove hard wrapping of paragraphs."
icon: "hardwrap.png"
title: "Wrap"
shell script file: "hardwrap.rb"
script interpreter: "/usr/bin/ruby"
after: "paste-result"
requirements: ["paste"]
options:
  - identifier: "column"
    type: "string"
    label: "Column"
    default value: "80"
  - identifier: "altcolumn"
    type: "string"
    label: "Alternate Column"
    default value: "70"
